code/air/config/routes.rb
OneWayAir::Application.routes.draw do

  get "sign_in" => 'sessions#new', :as => :sign_in

  post "sessions/create"

  get "sessions/destroy" => 'sessions#destroy', :as => :sign_out

  get '/auth/:provider/callback', to: 'sessions#create'

  resources :users
  # get "/my_profile" => 'users#show', :as => :user

  root to: 'flights#index'

end

code/air/app/models/flight.rb
class Flight < ActiveRecord::Base
  attr_accessible :arrival_airport, :departs_at, :departure_airport, :number, :seats

  MILEAGE_CHART = {
    "ORD-JFK" => 740,
    "ORD-LAX" => 1744,
    "ORD-SFO" => 1846,
    "JFK-LAX" => 2475,
    "JFK-SFO" => 2586,
    "LAX-SFO" => 338
  }

  before_create :calculate_miles

  def calculate_miles
    distance = MILEAGE_CHART["#{departure_airport}-#{arrival_airport}"]
    if distance.nil?
      distance = MILEAGE_CHART["#{arrival_airport}-#{departure_airport}"]
    end
    self.miles = distance || 0
  end
  # def miles
  #   distance = MILEAGE_CHART["#{departure_airport}-#{arrival_airport}"]
  #   if distance.nil?
  #     distance = MILEAGE_CHART["#{arrival_airport}-#{departure_airport}"]
  #   end
  #   distance
  # end

  def arrives_at
    self.departs_at + duration.minutes
  end

  def duration
    self.miles / 8
  end
end

code/air/app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :password

  # has_secure_password

  validates_uniqueness_of :name

end

code/air/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

code/air/app/controllers/flights_controller.rb
class FlightsController < ApplicationController

  def index
    @flights = Flight.order("number asc").page(params[:page]).per(10)
  end
end

code/air/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    data = request.env["omniauth.auth"]
    logger.info data['provider']
    logger.info data['uid']
    logger.info data['info']['nickname']

    user = User.find_by_name(data['info']['nickname'])
    if user.blank?
      user = User.create name: data['info']['nickname']
    end

    session[:user_id] = user.id
    redirect_to root_url
  end

  def destroy
    reset_session
    redirect_to root_url, notice: "See ya!"
  end
end

code/air/app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :authorize_user, :only => [:show, :edit, :update, :destroy]

  def authorize_user
    @user = User.find(params[:id])
    if @user.id != session[:user_id]
      redirect_to root_url, notice: "Nice Try"
    end
  end

  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

code/air/app/helpers/application_helper.rb
module ApplicationHelper
end

code/air/app/helpers/sessions_helper.rb
module SessionsHelper
end

code/air/app/helpers/users_helper.rb
module UsersHelper
end

code/air/app/views/flights/index.html.erb
<div class="row">
  <div class="span12">
    <h1 class="page-header">Today's Flight Schedule</h1>
    <%= paginate @flights %>

    <table class="table table-hover">
      <thead>
        <tr>
          <th>Flight #</th>
          <th>From</th>
          <th>Departs</th>
          <th>To</th>
          <th>Arrives</th>
          <th>Miles</th>
          <th>Duration</th>
          <th>Seats</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @flights.each do |flight| %>
          <tr>
            <td><%= flight.number %></td>
            <td><%= flight.departure_airport %></td>
            <td><%= flight.departs_at.strftime("%l:%M %P") %></td>
            <td><%= flight.arrival_airport %></td>
            <td><%= flight.arrives_at.strftime("%l:%M %P") %></td>
            <td><%= flight.miles %></td>
            <td><%= flight.duration %> minutes</td>
            <td><%= flight.seats %></td>
            <% if session[:user_id] %>
              <td><a class="btn btn-success">Book Now</a></td>
            <% else %>
              <td>Sign Up!</td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

code/air/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OneWayAir</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="http://bootswatch.com/united/bootstrap.min.css">
  <style type="text/css">
    body { padding-top: 60px; padding-bottom: 40px; }
  </style>
  <link href="http://twitter.github.com/bootstrap/assets/css/bootstrap-responsive.css" rel="stylesheet">

  <style type="text/css">
    .table thead th { font-size: 20px; background: #5484a7; color: white; text-align: center; height: 30px; padding: 12px; vertical-align: middle}
    .table td { text-align: center; }
  </style>
  <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
  <!--[if lt IE 9]>
    <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->

  <link rel="apple-touch-icon" sizes="72x72" href="http://twitter.github.com/bootstrap/assets/images/apple-touch-icon-72x72.png">
  <link rel="apple-touch-icon" sizes="114x114" href="http://twitter.github.com/bootstrap/assets/images/apple-touch-icon-114x114.png">

</head>
<body>
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand span2" href="/">OneWay Airlines</a>
        <div class="nav-collapse">
          <form class="navbar-search pull-left" action="">
            <input type="text" class="search-query span3" placeholder="Search by city or airport code">
          </form>
          <ul class="nav pull-right">
            <li><a href="/airports.html">Cities</a></li>
            <li><a href="/support.html">Customer Support</a></li>

            <% if session[:user_id] %>
              <li><%= link_to "My Profile", user_url(session[:user_id]) %></li>
              <li><%= link_to "Sign Out", sign_out_url %></li>
            <% else %>
              <li><%= link_to "Sign in with Twitter", "/auth/twitter" %></li>
              <!-- <li><%#= link_to "Sign Me Up!", new_user_url %></li> -->
              <!-- <li><%#= link_to "Sign In", sign_in_url %></li> -->
            <% end %>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>
  </div>

  <div class="container">

    <%= notice %>
    <%= yield %>

    <hr>

    <footer>
      <p>&copy;2013 OneWay Airlines.  Got a comment or suggestion?  Keep it to yourself!</p>
    </footer>
  </div> <!-- /container -->

</body>
</html>

code/air/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

code/air/app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

code/air/app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Password digest</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.password_digest %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

code/air/app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

code/air/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<h2>Profile for <%= @user.name %></h2>

<h2>Miles Earned: 0</h2>

<h2>Reservation History</h2>
<p>No reservations found.  You should get out more often.</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>